# Generated by Django 5.1.4 on 2024-12-29 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0038_eventextralink"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleSignOnSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("some_setting", models.CharField(default="A", max_length=10)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretalx_sso_settings",
                        to="event.event",
                    ),
                ),
            ],
        ),
    ]
